package com.app.ekhabeer.utils;

import org.json.JSONArray;

import java.util.ArrayList;
import java.util.HashMap;

public class Constants {

    public static final String BASE_URL = "http://ekhabeer.com/test/book_final/book_final/";
    public static final String IMAGE_BASE_URL = "http://ekhabeer.com/test/book_final/book_final/img/";
    public static final String BASE_URL_TWO = "functionApi.php";

    public static final String USER_LOGIN ="userLogin" ;
    public static final String GET_SUB_CATEGORIES ="getSubCategoryList" ;
    public static final String UPDATE_PROFILE ="updateProfile" ;
    public static final String GET_CONSULT_LIST_TIME ="getConsultListWithTime" ;
    public static final String GET_CONSULT_LIST ="getConsultListWithSubCat" ;
    public static final String GET_MESSAGES_LIST ="getAllMessageList" ;
    public static final String GET_MESSAGES_CONSUL ="messageUsersForConsultant" ;
    public static final String GET_MESSAGES_USERS ="messageConsultantForUsers" ;
    public static final String BOOK_APPOINTMENT ="bookAppointment" ;
    public static final String GET_PROFILE_INFO ="getProfileInfo" ;
    public static final String APPOINTMENT_LIST_CONSUL ="appointmentListForConsultant" ;
    public static final String APPOINTMENT_LIST_USER ="appointmentListForUser" ;
    public static final String STATUS_TYPE ="status_type" ;
    public static final String CONSULT_LOGIN ="consultantLogin" ;
    public static final String INSERT_MESSAGE ="insertMessage" ;
    public static final String INSERT_FEEDBACK ="insertFeedback" ;
    public static final String CONSULT_REGISTER ="consultRegister" ;
    public static final String USER_REGISTER ="userRegister" ;
    public static final Model model= new Model();

    public static final String CAT_ID ="cat_id" ;
    public static final String SUB_CAT_ID ="subcat_id" ;
    public static final String USER_ID ="user_id" ;
    public static final String USER_CONSULT_ID  ="userConsult_id" ;
    public static final String SUB_ID ="sub_id" ;
    public static final String TYPE ="type" ;
    public static final String ITEM_DATA ="item_data" ;
    public static final String ID ="id" ;
    public static final String CONS_ID ="cons_id" ;
    public static final String CONS_FIRSTNAME ="cons_firstname" ;
    public static final String CONS_LASTNAME ="cons_lastname" ;
    public static final String CONS_PROFILE ="cons_profile" ;
    public static final String USER_PROFILE ="user_profile" ;
    public static final String USER_FIRSTNAME ="user_firstname" ;
    public static final String USER_LASTNAME ="user_lastname" ;
    public static final String DATA ="data" ;
    public static final String DAYS ="days" ;
    public static final String STATUS ="status" ;
    public static final String MESSAGE ="message" ;
    public static final String MESSAGE_LIST ="message_list" ;
    public static final String CONSULTANT_ID ="consultant_id" ;
    public static final String APPOINT_ID ="appoint_id" ;
    public static final String FNAME ="fname" ;
    public static final String RATING ="rating" ;
    public static final String MNAME ="mname" ;
    public static final String NAME ="name" ;
    public static final String LNAME ="lname" ;
    public static final String DOB ="dob" ;
    public static final String DATE ="date" ;
    public static final String FEE ="fee" ;
    public static final String TIME ="time" ;
    public static final String REVIEW_TEXT ="review_text" ;
    public static final String AGE ="age" ;
    public static final String COUNTRY ="country" ;
    public static final String TO_TIME ="totime" ;
    public static final String FROM_TIME ="fromtime" ;
    public static final String GENDER ="gender" ;
    public static final String MOBILE ="mobile" ;
    public static final String BIO ="bio" ;
    public static final String SMOBILE ="smobile" ;
    public static final String EMAIL ="email" ;
    public static final String SENDER_ID ="sender_id" ;
    public static final String RECEIVER_ID ="receiver_id" ;
    public static final String CONTACT ="contact" ;
    public static final String SENDER_TYPE ="sender_type" ;
    public static final String READ_STATUS ="read_status" ;
    public static final String TIMESTAMP ="timestamp" ;
    public static final String PASSWORD ="password" ;
    public static final String PROFILE ="profile" ;
    public static final String CITY ="city" ;
    public static final String ZIPCODE ="zipcode" ;
    public static final String ADDRESS ="address" ;
    public static final String SPECIAL ="special" ;
    public static final String WEBSITE ="website" ;
    public static final String DEGREE ="degree" ;
    public static final String UNIVERSITY ="university" ;
    public static final String SUBSPECIAL ="subspecial" ;
    public static final String MEMBERSHIP ="membership" ;
    public static final String ACTIVITIES ="activities" ;
    public static final String LANGUAGE ="language" ;
    public static final String CATEGORY ="category" ;
    public static final String RESPONSE_TIME ="responsetime" ;
    public static final String SUBCATEGORY ="subcategory" ;
    public static final String ONE_EST_COST ="1estcost" ;
    public static final String THREE_EST_COST ="3estcost" ;
    public static final String THIRTY_EST_COST ="30estcost" ;
    public static final String FORTYFIVE_EST_COST ="45estcost" ;
    public static final String SIXTY_EST_COST ="60estcost" ;
    public static final String USER_NAME ="username" ;
    public static final String ACCESS ="access" ;
    public static final String CONSULTATION ="consultation" ;
    ArrayList<HashMap<String,String>> categories_list = new ArrayList();
}
